'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, User, ShieldCheck, TrendingUp, TrendingDown, CheckCircle2, Download } from 'lucide-react';
import api from '@/lib/api';
import toast from 'react-hot-toast';

export default function ApplicantPage() {
  const params = useParams();
  const router = useRouter();
  const [applicant, setApplicant] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchApplicantDetails = async () => {
      setLoading(true);
      try {
        const { data } = await api.get(`/lender/applicant/${params.id}`);
        setApplicant(data);
      } catch (err) {
        console.error('Failed to fetch applicant', err);
      } finally {
        setLoading(false);
      }
    };

    fetchApplicantDetails();
  }, [params.id]);

  if (loading) return <div className="flex justify-center p-12 text-[#64748B]">Loading applicant details...</div>;
  if (!applicant) return <div className="text-[#64748B] p-12 text-center">Applicant not found</div>;

  const getRiskBadge = (tier: string) => {
    switch (tier) {
      case 'Green': return 'badge badge-success';
      case 'Yellow': return 'badge badge-warning';
      case 'Red': return 'badge badge-danger';
      default: return 'badge';
    }
  };

  const handleDownload = () => {
    const report = `CREDITLENS APPLICANT REPORT
==============================
Name: ${applicant.name}
Email: ${applicant.email}
CreditLens Score: ${applicant.score}
Risk Tier: ${applicant.risk_tier} Risk
Income: ${applicant.income}
Employment: ${applicant.employment}

POSITIVE SIGNALS (HELPING)
${applicant.explainData.helping.map((h: any) => `- ${h.feature}: ${h.impact}`).join('\n')}

RISK FACTORS (HURTING)
${applicant.explainData.hurting.map((h: any) => `- ${h.feature}: +${h.impact}`).join('\n')}

Generated by CreditLens | ${new Date().toLocaleDateString()}`;
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CreditLens_Report_${applicant.name}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleLoanOffer = () => {
    toast.success(`Loan offer initiated for ${applicant.name}. They will be notified via their registered email.`);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      <Link href="/lender/dashboard" className="inline-flex items-center text-xs font-black uppercase tracking-wider text-[#64748B] hover:text-[#320070] transition-colors">
        <ArrowLeft className="mr-2 h-4 w-4" />
        Back to Dashboard
      </Link>

      <div className="card bg-white border-2 border-[#320070] shadow-[6px_6px_0px_0px_#320070] p-8">
        <div className="flex flex-col md:flex-row gap-6 items-start md:items-center justify-between border-b-2 border-[#f8f7f5] pb-6">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded border-2 border-[#320070] bg-[#ecebe8] flex items-center justify-center text-xl font-black text-[#320070] shadow-[2px_2px_0px_0px_rgba(0,0,0,0.15)]">
              {applicant.name.charAt(0)}
            </div>
            <div>
              <h1 className="text-2xl font-black uppercase tracking-tight text-[#320070]">{applicant.name}</h1>
              <p className="text-[#64748B] text-xs font-bold uppercase tracking-wider">{applicant.email}</p>
            </div>
          </div>
          
          <div className="flex flex-col items-end gap-1">
            <p className="text-[10px] font-extrabold uppercase tracking-wider text-[#64748B]">CreditLens Score</p>
            <div className="flex items-center gap-3">
              <span className={getRiskBadge(applicant.risk_tier)}>
                {applicant.risk_tier} Risk
              </span>
              <span className="text-4xl font-black text-[#320070]">{applicant.score}</span>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-8 pt-6">
          <div>
            <h3 className="font-black text-[#320070] mb-4 flex items-center gap-2 text-xs uppercase tracking-widest border-b border-[#ecebe8] pb-2">
              <User size={14} /> Borrower Profile
            </h3>
            <div className="space-y-4">
              <div>
                <p className="text-[10px] font-extrabold uppercase tracking-wider text-[#64748B] mb-0.5">Reported Income</p>
                <p className="font-bold text-sm text-[#320070]">{applicant.income.toLocaleString()}</p>
              </div>
              <div>
                <p className="text-[10px] font-extrabold uppercase tracking-wider text-[#64748B] mb-0.5">Employment Type</p>
                <p className="font-bold text-sm text-[#320070] uppercase tracking-wider">{applicant.employment}</p>
              </div>
              <div>
                <p className="text-[10px] font-extrabold uppercase tracking-wider text-[#64748B] mb-0.5">Data Sources Verified</p>
                <div className="flex gap-2 mt-1">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-[#f8f7f5] border-2 border-[#320070] rounded-sm text-[10px] font-bold uppercase tracking-wider text-[#320070]"><CheckCircle2 size={12} className="text-[#059669]" /> UPI History</span>
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-[#f8f7f5] border-2 border-[#320070] rounded-sm text-[10px] font-bold uppercase tracking-wider text-[#320070]"><CheckCircle2 size={12} className="text-[#059669]" /> Telecom</span>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-[#f8f7f5] rounded p-6 border-2 border-[#320070] shadow-[4px_4px_0px_0px_#320070]">
            <h3 className="font-black text-[#320070] mb-4 flex items-center gap-2 text-xs uppercase tracking-wider border-b border-[#320070] pb-2">
              <ShieldCheck size={16} className="text-[#7100eb]" /> Underwriting Decision
            </h3>
            
            <div className="space-y-4">
              <div>
                <div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider mb-2 text-[#059669]">
                  <TrendingUp size={14} /> Positive Signals (Helping)
                </div>
                <ul className="space-y-2">
                  {applicant.explainData.helping.map((h: any, i: number) => (
                    <li key={i} className="text-[10px] font-semibold flex justify-between bg-white px-3 py-2 rounded-sm border border-[#320070]">
                      <span className="text-[#320070] font-black uppercase tracking-wider">{h.feature.replace(/_/g, ' ')}</span>
                      <span className="font-mono text-[#059669] font-black">{h.impact}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider mb-2 text-[#EF476F] mt-4">
                  <TrendingDown size={14} /> Risk Factors (Hurting)
                </div>
                <ul className="space-y-2">
                  {applicant.explainData.hurting.map((h: any, i: number) => (
                    <li key={i} className="text-[10px] font-semibold flex justify-between bg-white px-3 py-2 rounded-sm border border-[#EF476F]">
                      <span className="text-[#320070] font-black uppercase tracking-wider">{h.feature.replace(/_/g, ' ')}</span>
                      <span className="font-mono text-[#EF476F] font-black">+{h.impact}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-4 border-t border-[#ecebe8] pt-6">
  <button
    onClick={handleDownload}
    className="btn btn-outline text-xs px-6 py-4 border-2 border-[#320070] text-[#320070] hover:bg-[#320070] hover:text-white flex items-center gap-2"
  >
    <Download size={16} /> Download Full Report
  </button>
  <button
    onClick={async () => {
      try {
        await api.post(`/lender/applicant/${params.id}/reject`);
        toast.success(`Application rejected for ${applicant.name}.`);
        router.push('/lender/dashboard');
      } catch (err) {
        toast.error('Failed to reject applicant');
      }
    }}
    className="btn text-xs px-6 py-4 border-2 border-[#EF476F] text-[#EF476F] hover:bg-[#EF476F] hover:text-white"
  >
    Reject Application
  </button>
  <button
    onClick={async () => {
      try {
        await api.post(`/lender/applicant/${params.id}/accept`);
        toast.success(`Loan offer initiated for ${applicant.name}. They will be notified via their registered email.`);
        router.push('/lender/dashboard');
      } catch (err) {
        toast.error('Failed to accept applicant');
      }
    }}
    className="btn btn-accent text-xs px-6 py-4 shadow-[3px_3px_0px_0px_#320070] hover:bg-[#7100eb] hover:text-white"
  >
    Initiate Loan Offer
  </button>
  </div>
    </div>);
}